force-app/main/default/objects/Case/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Loreal</label>
    <referenceTo>Product2__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product_Barcode__c.field-meta.xml
<CustomField>
    <fullName>Product_Barcode__c</fullName>
    <label>Product Barcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2__c/Product2__c.object-meta.xml
<CustomObject>
    <label>Product2</label>
    <nameField>
        <label>Product2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product2s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <externalId>true</externalId>
    <label>Barcode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CaseTriggerTest.cls
@IsTest
private class CaseTriggerTest {

    @IsTest
    static void testAfterInsert_enqueuesQueueable_forValidBarcode() {
        Test.setMock(HttpCalloutMock.class, new ProductApiMock());
        Account acc = new Account(
            Name = 'Test Consumer3'
        );
        insert acc;
        List<Case> casesToInsert = new List<Case>{
            new Case(Subject = 'Case 1',AccountId = acc.Id, Origin = 'Phone', Product_Barcode__c = '111111'),
            new Case(Subject = 'Case 2',AccountId = acc.Id, Origin = 'Email', Product_Barcode__c = null),
            new Case(Subject = 'Case 3',AccountId = acc.Id, Origin = 'Web', Product_Barcode__c = '222222')
        };
        Test.startTest();
        insert casesToInsert;
        Test.stopTest();
        Integer countProds = [SELECT count() FROM Product2__c WHERE Barcode__c = '3600523235214'];
        System.assertEquals(1, countProds);
    }
    
}