force-app/main/default/objects/Product2__c/Product2__c.object-meta.xml
<CustomObject>
    <label>Product2</label>
    <nameField>
        <label>Product2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product2s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <externalId>true</externalId>
    <label>Barcode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProductController.cls
public class ProductController {
    
    @AuraEnabled(cacheable=true)
    public static Product2__c getProduct(String barcode) {
        
        if (String.isBlank(barcode)) {
            return null;
        }

        List<Product2__c> products = [
            SELECT Id, Name, Barcode__c, Expiration_Date__c, Category__c
            FROM Product2__c
            WHERE Barcode__c = :barcode
            LIMIT 1
        ];
        return products.isEmpty() ? null : products[0];
    }
}